import type { RoomListItem } from '@/modules/room/types/ui'

export const roomItems: RoomListItem[] = [
  {
    id: 'anh-duc',
    title: 'Anh Đức IT',
    initials: 'AD',
    preview: '168966',
    time: '9:30 PM',
    color: 'from-[#a7a7a7] to-[#737373]',
  },
  {
    id: 'ag-task',
    title: 'AG Task',
    initials: 'AT',
    preview: 'Github Notification BOT: Repository: ant-group-developer/ag-task...',
    time: '6:34 PM',
    color: 'from-[#ffb23f] to-[#ff7a45]',
  },
  {
    id: 'ag-hrm',
    title: 'AG HRM',
    initials: 'AH',
    preview: 'Github Notification BOT: Repository: ant-group-developer/ag-hrms...',
    time: '6:32 PM',
    active: true,
    color: 'from-[#ff74a5] to-[#d959b8]',
  },
  {
    id: 'ag-release',
    title: 'AG Release',
    initials: 'AR',
    preview: 'You: em đây fe rồi ạ',
    time: '5:34 PM',
    color: 'from-[#9278ee] to-[#6d5ee7]',
    checks: true,
  },
  {
    id: 'qlph',
    title: 'QLPH NLoan',
    initials: 'QN',
    preview: 'cũng tạm thôi',
    time: '5:31 PM',
    color: 'from-[#71d06b] to-[#34b84d]',
    checks: true,
  },
  {
    id: 'release-prod',
    title: 'AG Release phát hành',
    initials: 'AH',
    preview: 'QLPH: Photo',
    time: '5:26 PM',
    color: 'from-[#72d86a] to-[#30b34b]',
  },
  {
    id: 'be-em',
    title: 'Bé Em',
    initials: 'BE',
    preview: 'ọeee',
    time: '5:25 PM',
    color: 'from-[#9d9d9d] to-[#505050]',
  },
  {
    id: 'an-trua',
    title: 'nhóm ăn trưa',
    initials: 'NT',
    preview: 'QLPH_Nguyễn Thọ Hùng: 🙏🙏🙏',
    time: '2:05 PM',
    color: 'from-[#ff7c61] to-[#ed4f42]',
  },
  {
    id: 'nguyen-gia-khien',
    title: 'Nguyễn Gia Khiên - FE',
    initials: 'NF',
    preview: 'đúng r',
    time: '2:05 PM',
    color: 'from-[#57c7df] to-[#32a2c7]',
  },
]
